### ISSUE TITLE
Installation instructions for Docker are missing

### ISSUE THREAD

**Issue by mmikhasenko** [JohannesBuchner/PracticalInferenceForResearchersInThePhysicalSciencesCourse#4]
Tbh, I doubt someone will be running Docker. It this is the case, you can remove the Docker option and leave just a link to a docker for the installation hints.

**Comment by JohannesBuchner** [comment]
I don't understand. In what sense are the instructions missing? They are here:
https://johannesbuchner.github.io/PracticalInferenceForResearchersInThePhysicalSciencesCourse/install.html#option-2-with-docker

Why do you doubt someone will run docker? What do you mean by "a link to a docker"? Push an image to dockerhub?

**Comment by mmikhasenko** [comment]
Indeed, they are there in the same block as the Docker script.
Do yo mind separating?

**Comment by JohannesBuchner** [comment]
I think I fixed this now.
